# Generated by Django 6.0 on 2026-04-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('administrator', 'Администратор'), ('curator', 'Куратор'), ('employee', 'Сотрудник')], default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
