# Generated by Django 6.0 on 2026-04-09 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория материала',
                'verbose_name_plural': 'Категории материалов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Слаг')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('material_format', models.CharField(choices=[('article', 'Статья'), ('guide', 'Инструкция'), ('checklist', 'Чек-лист'), ('video', 'Видео'), ('presentation', 'Презентация')], default='article', max_length=20, verbose_name='Формат')),
                ('estimated_minutes', models.PositiveIntegerField(default=10, verbose_name='Оценка времени, мин')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_materials', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='app.materialcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Обучающий материал',
                'verbose_name_plural': 'Обучающие материалы',
                'ordering': ('-created_at',),
            },
        ),
    ]
