# Generated by Django 6.0 on 2026-04-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_materialcategory_learningmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='materials/attachments/', verbose_name='Файл (PDF или DOCX)'),
        ),
    ]
