# Generated by Django 6.0 on 2026-04-10 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_learningmaterial_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание (устаревшее, для совместимости)'),
        ),
        # Таблица app_materialpage могла уже быть создана ранней миграцией — не дублируем CREATE TABLE в БД,
        # только синхронизируем состояние миграций Django.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='MaterialPage',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                        (
                            'title',
                            models.CharField(
                                blank=True,
                                max_length=255,
                                verbose_name='Заголовок страницы',
                            ),
                        ),
                        ('body', models.TextField(blank=True, verbose_name='Текст страницы')),
                        (
                            'image',
                            models.ImageField(
                                blank=True,
                                null=True,
                                upload_to='materials/pages/',
                                verbose_name='Изображение',
                            ),
                        ),
                        (
                            'quiz_question',
                            models.TextField(blank=True, verbose_name='Вопрос мини-теста'),
                        ),
                        (
                            'quiz_choice_1',
                            models.TextField(blank=True, verbose_name='Вариант 1'),
                        ),
                        (
                            'quiz_choice_2',
                            models.TextField(blank=True, verbose_name='Вариант 2'),
                        ),
                        (
                            'quiz_choice_3',
                            models.TextField(blank=True, verbose_name='Вариант 3'),
                        ),
                        (
                            'quiz_choice_4',
                            models.TextField(blank=True, verbose_name='Вариант 4'),
                        ),
                        (
                            'quiz_correct',
                            models.PositiveSmallIntegerField(
                                blank=True,
                                choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')],
                                null=True,
                                verbose_name='Верный ответ (номер варианта)',
                            ),
                        ),
                        (
                            'material',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='pages',
                                to='app.learningmaterial',
                                verbose_name='Материал',
                            ),
                        ),
                    ],
                    options={
                        'verbose_name': 'Страница материала',
                        'verbose_name_plural': 'Страницы материала',
                        'ordering': ('order', 'id'),
                    },
                ),
            ],
        ),
    ]
