# Generated by Django 5.2.2 on 2026-04-11 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_learningmaterial_content_materialpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMaterialPageQuizCompletion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("selected_choice", models.PositiveSmallIntegerField(verbose_name="Выбранный верный вариант")),
                ("completed_at", models.DateTimeField(auto_now_add=True, verbose_name="Пройдено")),
                (
                    "page",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_completions",
                        to="app.materialpage",
                        verbose_name="Страница",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_quiz_completions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пройденный тест страницы",
                "verbose_name_plural": "Пройденные тесты страниц",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "page"), name="uniq_user_page_quiz_completion")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserMaterialProgress",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_page_index", models.PositiveIntegerField(default=1, verbose_name="Последняя страница")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress_records",
                        to="app.learningmaterial",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_progress_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по материалу",
                "verbose_name_plural": "Прогресс по материалам",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "material"), name="uniq_user_material_progress")
                ],
            },
        ),
    ]
