# Generated by Django 6.0 on 2026-04-11 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_material_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaterialpagequizcompletion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usermaterialprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='KnowledgeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Слаг')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('estimated_minutes', models.PositiveIntegerField(default=15, verbose_name='Оценка времени, мин')),
                ('passing_score_percent', models.PositiveSmallIntegerField(default=60, help_text='Минимальный процент верных ответов для успешного прохождения.', verbose_name='Проходной балл, %')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_knowledge_tests', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_tests', to='app.materialcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('score_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Результат, %')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='Пройден')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='app.knowledgetest', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки тестов',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.knowledgetest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTestAnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choices', to='app.knowledgetestquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа (тест)',
                'verbose_name_plural': 'Варианты ответа (тест)',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTestAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.knowledgetestattempt', verbose_name='Попытка')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_selections', to='app.knowledgetestanswerchoice', verbose_name='Выбранный вариант')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='app.knowledgetestquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ в попытке теста',
                'verbose_name_plural': 'Ответы в попытках тестов',
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_knowledge_test_attempt_question')],
            },
        ),
    ]
