# Generated by Django 5.2.2 on 2026-04-11 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_usermaterialpagequizcompletion_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackSubmission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Имя")),
                ("phone", models.CharField(blank=True, max_length=40, verbose_name="Телефон")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Электронная почта")),
                ("subject", models.CharField(max_length=255, verbose_name="Тема")),
                ("message", models.TextField(verbose_name="Текст сообщения")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("resolved", "Выполнено"),
                            ("closed", "Закрыто"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата отправки")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь (если был авторизован)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обращение (обратная связь)",
                "verbose_name_plural": "Обращения (обратная связь)",
                "ordering": ("-created_at",),
            },
        ),
    ]
