# Generated by Django 6.0 on 2026-04-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_feedback_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacksubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
